# Generated by Django 2.0.1 on 2018-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
