# Generated by Django 2.0.1 on 2018-03-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula'), ('PA', 'Pasaporte'), ('CE', 'Cédula de extranjería')], default='CC', max_length=50),
        ),
    ]
