# Generated by Django 2.0.1 on 2018-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='document_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(default='CC', max_length=50),
        ),
    ]
