# Generated by Django 2.0.1 on 2018-03-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profile_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_points',
        ),
    ]
