# Generated by Django 2.0.1 on 2018-03-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
