# Generated by Django 2.0.1 on 2018-03-11 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='allowed_participants',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.CharField(choices=[('5_Participantes', 'A'), ('2_Participantes', 'B'), ('1_Participante', 'C')], max_length=2),
        ),
    ]
