# Generated by Django 2.0.1 on 2018-03-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_profile_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fill_groups',
            field=models.BooleanField(default=False),
        ),
    ]
