# Generated by Django 2.0.1 on 2018-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_profile_fill_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fill_groups',
            new_name='eights_filled',
        ),
        migrations.AddField(
            model_name='profile',
            name='final_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourths_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='semi_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trd_fth_filled',
            field=models.BooleanField(default=False),
        ),
    ]
