# Generated by Django 2.0.1 on 2018-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20180401_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eights_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='final_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourths_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='semi_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='trd_fth_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
