# Generated by Django 2.0.1 on 2018-03-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('clients', '0009_remove_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(default='CC', max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clients.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
