# Generated by Django 2.0.1 on 2018-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20180401_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eights_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='final_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourths_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='semi_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trd_fth_created',
            field=models.BooleanField(default=False),
        ),
    ]
