# Generated by Django 2.0.1 on 2018-04-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20180410_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eights_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='final_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fourths_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semi_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trd_fth_created',
        ),
    ]
