# Generated by Django 2.0.1 on 2018-03-11 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0010_auto_20180311_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='UserInfo',
        ),
    ]
