# Generated by Django 2.0.1 on 2018-03-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20180311_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
