# Generated by Django 2.0.1 on 2018-03-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20180312_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('Cédula', 'CC'), ('Pasaporte', 'PA'), ('Cedula_extranjería', 'CE')], default='CC', max_length=50),
        ),
    ]
