# Generated by Django 2.0.1 on 2018-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20180412_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
