# Generated by Django 2.0.1 on 2018-03-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20180312_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
