# Generated by Django 2.0.1 on 2018-04-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20180412_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
    ]
