# Generated by Django 2.0.1 on 2018-03-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
