# Generated by Django 2.0.1 on 2018-03-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_profile_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document_number',
        ),
    ]
