# Generated by Django 2.0.1 on 2018-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_remove_client_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.CharField(choices=[('10_Participantes', 'A'), ('5_Participantes', 'B'), ('3_Participante', 'C')], max_length=50),
        ),
    ]
