# Generated by Django 2.0.1 on 2018-04-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20180417_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile',
            new_name='prof',
        ),
    ]
