# Generated by Django 2.0.1 on 2018-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_client_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
