# Generated by Django 2.0.1 on 2018-04-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20180420_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsConditions',
        ),
        migrations.AlterField(
            model_name='client',
            name='legal',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
