# Generated by Django 2.0.1 on 2018-03-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3_y_4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50)),
                ('team_one', models.CharField(max_length=255)),
                ('team_two', models.CharField(max_length=255)),
                ('goals_one', models.PositiveIntegerField()),
                ('goals_two', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('A', 'Grupo A'), ('GROUP_B', 'Grupo B'), ('GROUP_C', 'Grupo C'), ('GROUP_D', 'Grupo D'), ('GROUP_E', 'Grupo E'), ('GROUP_F', 'Grupo F'), ('GROUP_G', 'Grupo G'), ('GROUP_H', 'Grupo H')], max_length=50)),
            ],
        ),
    ]
