# Generated by Django 2.0.1 on 2018-03-16 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3_y_4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('A', 'Grupo A'), ('GROUP_B', 'Grupo B'), ('GROUP_C', 'Grupo C'), ('GROUP_D', 'Grupo D'), ('GROUP_E', 'Grupo E'), ('GROUP_F', 'Grupo F'), ('GROUP_G', 'Grupo G'), ('GROUP_H', 'Grupo H')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_score', models.PositiveIntegerField()),
                ('team_two_score', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guessed', to='world_cup.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_one', to='world_cup.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_two', to='world_cup.Team'),
        ),
    ]
