# Generated by Django 2.0.1 on 2018-03-22 02:54

from django.db import migrations

def create_teams(apps, schema_editor):
    group_teams = {'A': ['Rusia', 'Arabia Saudí','Egipto', 'Uruguay'],
            'B': ['Portugal', 'España', 'Marruecos', 'Irán'],
            'C': ['Francia', 'Australia', 'Perú', 'Dinamarca'],
            'D': ['Argentina', 'Islandia', 'Croacia', 'Nigeria'],
            'E': ['Brasil', 'Suiza', 'Costa Rica', 'Serbia'],
            'F': ['Alemania', 'México', 'Suecia', 'Corea del Sur'],
            'G': ['Bélgica', 'Panamá', 'Túnez', 'Inglaterra'],
            'H': ['Polonia', 'Senegal', 'Colombia', 'Japón']}

    for group, teams in group_teams.items():
        for team in teams:
            new_team = Team(country=group,
                            group=team)
            new_team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_teams),
    ]
