# Generated by Django 2.0.1 on 2018-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=50),
        ),
    ]
