# Generated by Django 2.0.1 on 2018-03-20 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world_cup', '0003_auto_20180320_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3_y_4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50)),
                ('group', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=50, null=True)),
                ('team_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_team_one', to='world_cup.Team')),
                ('team_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_team_two', to='world_cup.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3_y_4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50)),
                ('group', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=50, null=True)),
                ('team_one_score', models.PositiveIntegerField()),
                ('team_two_score', models.PositiveIntegerField()),
                ('team_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_team_one', to='world_cup.Team')),
                ('team_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_team_two', to='world_cup.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two',
        ),
        migrations.RemoveField(
            model_name='userguess',
            name='match',
        ),
        migrations.RemoveField(
            model_name='userguess',
            name='user',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='UserGuess',
        ),
    ]
