# Generated by Django 2.0.1 on 2018-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0004_auto_20180320_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmatch',
            name='team_one_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realmatch',
            name='team_two_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='gambled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='team_one_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='team_two_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
