# Generated by Django 2.0.1 on 2018-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0004_auto_20180322_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmatch',
            name='phase',
            field=models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3y4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='phase',
            field=models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semi', 'Semifinal'), ('3y4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50),
        ),
    ]
