# Generated by Django 2.0.1 on 2018-03-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0005_auto_20180327_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realmatch',
            options={'verbose_name': 'RealMatch', 'verbose_name_plural': 'RealMatches'},
        ),
    ]
