# Generated by Django 2.0.1 on 2018-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0006_auto_20180328_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermatch',
            options={'verbose_name': 'UserMatch', 'verbose_name_plural': 'UserMatches'},
        ),
    ]
