# Generated by Django 2.0.1 on 2018-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0007_auto_20180328_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmatch',
            name='label',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
