# Generated by Django 2.0.1 on 2018-04-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0010_auto_20180401_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(default='U+1F680', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userteam',
            name='emoji',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
