# Generated by Django 2.0.1 on 2018-04-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0012_auto_20180401_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_winner', to='world_cup.Team'),
        ),
        migrations.AddField(
            model_name='usermatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_winner', to='world_cup.UserTeam'),
        ),
        migrations.AlterField(
            model_name='realmatch',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='realmatch',
            name='phase',
            field=models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Fourths', 'Cuartos'), ('Semi', 'Semifinal'), ('3y4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='label',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='phase',
            field=models.CharField(choices=[('Groups', 'Grupos'), ('Eights', 'Octavos'), ('Fourths', 'Cuartos'), ('Semi', 'Semifinal'), ('3y4', 'Puesto 3 y 4'), ('Finals', 'Final')], max_length=50),
        ),
    ]
