# Generated by Django 2.0.1 on 2018-04-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0013_auto_20180405_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realmatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='usermatch',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_loser', to='world_cup.UserTeam'),
        ),
    ]
