# Generated by Django 2.0.1 on 2018-04-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0016_auto_20180405_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmatch',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_loser', to='world_cup.Team'),
        ),
        migrations.AlterField(
            model_name='realmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_winner', to='world_cup.Team'),
        ),
    ]
