# Generated by Django 2.0.1 on 2018-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0018_auto_20180410_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realmatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='usermatch',
            name='real',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userteam',
            name='real',
            field=models.BooleanField(default=False),
        ),
    ]
