# Generated by Django 2.0.1 on 2018-04-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0020_permisions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='permisions',
            new_name='DatePermisions',
        ),
    ]
