# Generated by Django 2.0.1 on 2018-04-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0021_auto_20180413_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatePermisions',
            new_name='DatePermissions',
        ),
    ]
