# Generated by Django 2.0.1 on 2018-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0022_auto_20180413_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepermissions',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
