# Generated by Django 2.0.1 on 2018-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0023_auto_20180413_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datepermissions',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='datepermissions',
            name='phase',
        ),
        migrations.AddField(
            model_name='datepermissions',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
